sudo: false
language: node_js
node_js:
  - '4'
before_install:
  - npm i -g npm@^3.0.0
cache:
  directories:
    - node_modules
before_script:
  - npm prune
notifications:
  email: false
script:
  - npm run check
after_success:
  - npm run report-coverage
branches:
  only:
    - master

